# Integración STSIVA_2026 - Modelos de Difusión
# Hiperparámetros base de los experimentos de Diffusion Posterior Sampling

# Definición de la U-Net incondicional pre-entrenada
diffusion_model:
  image_size: 32  # Resolución del mapa de conductividad (32x32 para prototipos rápidos)
  weights_path: "../STSIVA_2026-main/weights/e_1000_bs_64_lr_0.0003_seed_2_img_32_schedule_cosine_gpu_0_c_3_si_100/checkpoints/latest.pth.tar"
  num_channels_model: 64

# Configuración del Solucionador Inverso (Reconstrucción)
sampling:
  algo: "DPS"  # Opciones: "DPS", "DDNM", "DiffPIR"
  sampling_steps: 1000
  dps_scale: 0.05       # Peso de la guía física (Data Consistency) en DPS
  # dps_scale controla qué tan agresivo corrigen las medidas V_meas al Prior Difusional!
  
  # Si probaras con DiffPIR/DDNM
  ddnm_eta: 1.0
  CG_iters_diffpir: 5
  noise_level_img: 0.0

# Condiciones del Problema ERT
ert:
  num_electrodes: 45
  # ground_truth_idx es el ID de un mapa "ejemplo" si se tiene dataset
  ground_truth_idx: 0
  
logging:
  use_wandb: "False"
  project_name: "ERT_Diffusion_STSIVA"
